import { Client } from '@neondatabase/serverless';

const listings = [
  {
    name: 'Blue Cross Animal Clinic',
    slug: 'blue-cross-animal-clinic-albuquerque',
    city: 'Albuquerque', citySlug: 'albuquerque', state: 'NM',
    address: '1670 University Blvd NE, Albuquerque, NM 87102',
    phone: '(505) 255-5250', website: 'https://bluecrossvetnm.com',
    description: 'Full-service small animal clinic offering medical exams, surgery, dentistry, radiology, acupuncture, and on-site laboratory diagnostics.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'surgery', 'acupuncture'],
  },
  {
    name: 'Juan Tabo Animal Clinic',
    slug: 'juan-tabo-animal-clinic-albuquerque',
    city: 'Albuquerque', citySlug: 'albuquerque', state: 'NM',
    address: '3804 Juan Tabo Blvd NE Suite A, Albuquerque, NM 87111',
    phone: '(505) 296-0715', website: 'https://www.juantaboanimalclinic.com',
    description: 'Full-service general practice veterinary clinic serving Albuquerque\'s Northeast Heights seven days a week.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'dogs', 'cats'],
  },
  {
    name: 'Eubank Animal Clinic',
    slug: 'eubank-animal-clinic-albuquerque',
    city: 'Albuquerque', citySlug: 'albuquerque', state: 'NM',
    address: '1601 Eubank Blvd NE, Albuquerque, NM 87112',
    phone: '(505) 296-0715', website: 'https://www.eubankanimalclinic.com',
    description: 'Independent small animal clinic providing comprehensive general veterinary care for dogs and cats in Albuquerque.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'dogs', 'cats'],
  },
  {
    name: "Boofy's Best for Pets",
    slug: 'boofys-best-for-pets-albuquerque',
    city: 'Albuquerque', citySlug: 'albuquerque', state: 'NM',
    address: '4900 Cutler Ave NE Ste F2, Albuquerque, NM 87110',
    phone: '(505) 884-3855', website: 'https://boofysbest.com',
    description: 'Locally owned natural pet food store open since 2010, specializing in raw dog and cat food, holistic treats, and supplies for dogs, cats, rabbits, and birds.',
    categorySlug: 'pet-supply', featured: false, tags: ['natural', 'raw-food', 'independent'],
  },
  {
    name: 'Long Leash on Life',
    slug: 'long-leash-on-life-albuquerque',
    city: 'Albuquerque', citySlug: 'albuquerque', state: 'NM',
    address: '9800 Montgomery Blvd NE Suite 13, Albuquerque, NM 87111',
    phone: '(505) 299-8800', website: 'https://www.longleashonlife.com',
    description: "One of the Southwest's largest independent pet health food stores, focusing on healthy foods, positive training, and enrichment for dogs and cats.",
    categorySlug: 'pet-supply', featured: false, tags: ['natural', 'independent', 'boutique'],
  },
  {
    name: "Beck 'n Call Pet Services",
    slug: 'beck-n-call-pet-services-albuquerque',
    city: 'Albuquerque', citySlug: 'albuquerque', state: 'NM',
    address: '9308 Susan Ave SE, Albuquerque, NM 87123',
    phone: '(505) 294-5004', website: 'https://www.beckncall.com',
    description: 'Personalized enrichment day care and boarding for dogs, offering cage-free play environments and individual attention.',
    categorySlug: 'boarding-daycare', featured: false, tags: ['daycare', 'dogs', 'enrichment'],
  },
  {
    name: 'Pet BnD Albuquerque',
    slug: 'pet-bnd-albuquerque',
    city: 'Albuquerque', citySlug: 'albuquerque', state: 'NM',
    address: '4401 Yale Blvd NE, Albuquerque, NM 87107',
    phone: '(505) 303-0554', website: 'https://www.petbnd.com',
    description: "Full-service dog boarding, daycare, training, and grooming facility in Albuquerque's North Valley.",
    categorySlug: 'boarding-daycare', featured: false, tags: ['boarding', 'grooming', 'training'],
  },
  {
    name: 'Hotel Albuquerque at Old Town',
    slug: 'hotel-albuquerque-at-old-town',
    city: 'Albuquerque', citySlug: 'albuquerque', state: 'NM',
    address: '800 Rio Grande Blvd NW, Albuquerque, NM 87104',
    phone: '(505) 843-6300', website: 'https://www.hotelabq.com',
    description: 'Historic full-service hotel adjacent to Old Town Albuquerque welcoming dogs with pet-friendly designated rooms.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['dogs', 'historic', 'full-service'],
  },
  {
    name: 'Nativo Lodge',
    slug: 'nativo-lodge-albuquerque',
    city: 'Albuquerque', citySlug: 'albuquerque', state: 'NM',
    address: '6000 Pan American Fwy NE, Albuquerque, NM 87109',
    phone: '(505) 798-4300', website: 'https://www.nativolodge.com',
    description: 'Southwestern-themed hotel welcoming up to two dogs up to 65 lbs, with treats and bowls at the front desk and a grassy pet relief area.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['dogs', 'pet-package', 'southwest'],
  },
  {
    name: 'Gruda Veterinary Hospital',
    slug: 'gruda-veterinary-hospital-santa-fe',
    city: 'Santa Fe', citySlug: 'santa-fe', state: 'NM',
    address: '9 Rumble Rd, Santa Fe, NM 87508',
    phone: '(505) 471-4400', website: 'https://grudavet.com',
    description: 'Independent private practice offering routine wellness, internal medicine, surgery, oncology, orthopedics, acupuncture, and chiropractic care for dogs, cats, and exotics.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'surgery', 'exotics'],
  },
  {
    name: 'Santa Fe Animal Hospital',
    slug: 'santa-fe-animal-hospital',
    city: 'Santa Fe', citySlug: 'santa-fe', state: 'NM',
    address: '1311 Osage Ave, Santa Fe, NM 87505',
    phone: '(505) 988-9644', website: 'https://santafeanimalhospital.com',
    description: 'Full-service small animal hospital equipped with advanced diagnostics, in-house lab, digital radiography, and abdominal ultrasound.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'diagnostics', 'dogs'],
  },
  {
    name: 'The Critters & Me',
    slug: 'the-critters-and-me-santa-fe',
    city: 'Santa Fe', citySlug: 'santa-fe', state: 'NM',
    address: '1403 Agua Fria St, Santa Fe, NM 87505',
    phone: '(505) 982-5040', website: 'https://crittersandme.com',
    description: 'Independent pet food and supply shop specializing in natural foods, organic feeds, homeopathic remedies, herbs, and natural supplements for dogs and cats.',
    categorySlug: 'pet-supply', featured: false, tags: ['natural', 'independent', 'holistic'],
  },
  {
    name: "Tulliver's Pet Food Emporium",
    slug: 'tullivers-pet-food-santa-fe',
    city: 'Santa Fe', citySlug: 'santa-fe', state: 'NM',
    address: '807 Cerrillos Rd, Santa Fe, NM 87505',
    phone: '(505) 992-3388', website: 'https://tulliverspetfood.com',
    description: "Santa Fe's trusted natural and holistic pet food store carrying premium food, raw and frozen diets, treats, and supplies for dogs and cats.",
    categorySlug: 'pet-supply', featured: false, tags: ['natural', 'raw-food', 'independent'],
  },
  {
    name: 'Top Dog Pet Resort',
    slug: 'top-dog-pet-resort-santa-fe',
    city: 'Santa Fe', citySlug: 'santa-fe', state: 'NM',
    address: '27694 W Frontage Rd, Santa Fe, NM 87507',
    phone: '(505) 303-3828', website: 'https://topdogsantafe.com',
    description: 'Premium boarding and daycare resort on 2.7 acres with architect-designed suites, individual exercise, grooming, and 24/7 on-site care.',
    categorySlug: 'boarding-daycare', featured: false, tags: ['boarding', 'grooming', 'luxury'],
  },
  {
    name: 'Santa Fe Tails',
    slug: 'santa-fe-tails',
    city: 'Santa Fe', citySlug: 'santa-fe', state: 'NM',
    address: '2109 Warner Cir, Santa Fe, NM 87505',
    phone: '(505) 820-0731', website: 'https://santafetails.com',
    description: 'Full-service pet daycare, boarding, and training facility serving Santa Fe dogs and cats with enrichment and socialization programs.',
    categorySlug: 'boarding-daycare', featured: false, tags: ['daycare', 'boarding', 'training'],
  },
  {
    name: 'Inn of the Turquoise Bear',
    slug: 'inn-of-the-turquoise-bear-santa-fe',
    city: 'Santa Fe', citySlug: 'santa-fe', state: 'NM',
    address: '342 E Buena Vista St, Santa Fe, NM 87505',
    phone: '(505) 983-0798', website: 'https://www.turquoisebear.com',
    description: 'Historic B&B on a rambling adobe estate near the Santa Fe Plaza, welcoming pets with a $30/day pet amenity fee.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['bed-and-breakfast', 'historic', 'boutique'],
  },
  {
    name: 'El Rey Court',
    slug: 'el-rey-court-santa-fe',
    city: 'Santa Fe', citySlug: 'santa-fe', state: 'NM',
    address: '1862 Cerrillos Rd, Santa Fe, NM 87505',
    phone: '(505) 982-1931', website: 'https://elreycourt.com',
    description: 'Iconic 1936 Route 66 motor court boutique hotel with 86 unique rooms and suites, welcoming up to two dogs with a $50 per-stay pet fee.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['boutique', 'dogs', 'historic'],
  },
  {
    name: 'East Lohman Veterinary Clinic',
    slug: 'east-lohman-veterinary-clinic-las-cruces',
    city: 'Las Cruces', citySlug: 'las-cruces', state: 'NM',
    address: '1700 E Lohman Ave, Las Cruces, NM 88001',
    phone: '(575) 523-5654', website: 'https://www.eastlohmanveterinaryclinic.com',
    description: 'Family-owned small animal clinic serving Las Cruces since 1977, providing care for dogs, cats, and exotic patients.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'exotics', 'independent'],
  },
  {
    name: 'Schumacher Veterinary Clinic',
    slug: 'schumacher-veterinary-clinic-las-cruces',
    city: 'Las Cruces', citySlug: 'las-cruces', state: 'NM',
    address: '701 S Valley Dr, Las Cruces, NM 88005',
    phone: '(575) 524-2894', website: 'https://www.schumacherveterinaryclinic.com',
    description: 'Full-service veterinary practice in Las Cruces offering comprehensive medical and surgical services for both small and large animals.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'surgery', 'large-animals'],
  },
  {
    name: 'Better Life Pet Foods',
    slug: 'better-life-pet-foods-las-cruces',
    city: 'Las Cruces', citySlug: 'las-cruces', state: 'NM',
    address: '315 S Telshor Blvd Ste C, Las Cruces, NM 88011',
    phone: '(575) 522-0115', website: 'https://betterlifenaturalpetfoods.com',
    description: 'Independent natural pet food store offering premium food, grooming, feline boarding, and a do-it-yourself dog wash station.',
    categorySlug: 'pet-supply', featured: false, tags: ['natural', 'grooming', 'independent'],
  },
  {
    name: 'Your Pet Space',
    slug: 'your-pet-space-las-cruces',
    city: 'Las Cruces', citySlug: 'las-cruces', state: 'NM',
    address: '2601 W Hadley Ave, Las Cruces, NM 88007',
    phone: '(575) 652-4404', website: 'https://www.yourpetspace.com',
    description: 'Indoor/outdoor pet facility offering daycare, boarding, grooming, and sitting for dogs, cats, and other animals.',
    categorySlug: 'boarding-daycare', featured: false, tags: ['daycare', 'boarding', 'cats'],
  },
  {
    name: 'Animal Haven Lodge & Salon',
    slug: 'animal-haven-lodge-las-cruces',
    city: 'Las Cruces', citySlug: 'las-cruces', state: 'NM',
    address: '3027 N Valley Dr, Las Cruces, NM 88007',
    phone: '(575) 523-0034', website: 'https://www.animalhavenlodge.com',
    description: 'Full-service pet facility providing dog and cat daycare, overnight boarding, grooming, training, and in-home pet care services.',
    categorySlug: 'boarding-daycare', featured: false, tags: ['boarding', 'grooming', 'training'],
  },
  {
    name: 'Hotel Encanto de Las Cruces',
    slug: 'hotel-encanto-de-las-cruces',
    city: 'Las Cruces', citySlug: 'las-cruces', state: 'NM',
    address: '705 S Telshor Blvd, Las Cruces, NM 88011',
    phone: '(575) 522-4300', website: 'https://www.hotelencanto.com',
    description: 'Upscale full-service hotel welcoming dogs up to 65 lbs, providing a pet bed, blanket, and treats for canine guests.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['dogs', 'luxury', 'full-service'],
  },
  {
    name: 'Best Western Mission Inn Las Cruces',
    slug: 'best-western-mission-inn-las-cruces',
    city: 'Las Cruces', citySlug: 'las-cruces', state: 'NM',
    address: '1120 N Telshor Blvd, Las Cruces, NM 88011',
    phone: '(575) 524-8591', website: 'https://www.bestwestern.com/en_US/book/hotels-in-las-cruces/best-western-mission-inn/propertyCode.32049.html',
    description: 'Pet-friendly hotel allowing up to two pets under 80 lbs with a grassy pet relief area and waste stations on-site.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['dogs', 'cats', 'affordable'],
  },
  {
    name: 'Taos Veterinary Clinic',
    slug: 'taos-veterinary-clinic',
    city: 'Taos', citySlug: 'taos', state: 'NM',
    address: '41 N Hwy 522, Taos, NM 87571',
    phone: '(575) 758-7310', website: 'https://taosvetclinic.com',
    description: 'Full-service veterinary facility serving Taos and surrounding communities for over 40 years, offering routine, surgical, and emergency care.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'surgery', 'emergency'],
  },
  {
    name: 'Salazar Road Veterinary Clinic',
    slug: 'salazar-road-veterinary-clinic-taos',
    city: 'Taos', citySlug: 'taos', state: 'NM',
    address: '1025 Salazar Rd, Taos, NM 87571',
    phone: '(575) 758-9115', website: 'https://taosvetclinic.com',
    description: 'General practice veterinary clinic serving the Taos community with routine wellness and medical care for small animals.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'dogs', 'cats'],
  },
  {
    name: 'Blue Sky Pet & Feed Supply',
    slug: 'blue-sky-pet-and-feed-taos',
    city: 'Taos', citySlug: 'taos', state: 'NM',
    address: '214 Paseo Del Pueblo Sur, Taos, NM 87571',
    phone: '(575) 758-1841', website: 'https://www.blueskypetandfeed.com',
    description: 'Locally owned and operated pet and livestock supply store voted Best of Taos multiple years, offering pet treats, toys, grooming supplies, and feed.',
    categorySlug: 'pet-supply', featured: false, tags: ['independent', 'grooming', 'feed'],
  },
  {
    name: 'Taos Tack & Pet Supply',
    slug: 'taos-tack-and-pet-supply',
    city: 'Taos', citySlug: 'taos', state: 'NM',
    address: '710 Paseo Del Pueblo Sur, Taos, NM 87571',
    phone: '(575) 737-9798', website: 'https://taostackandpetsupply.com',
    description: "Full-service pet and tack store carrying premium pet foods, livestock feed, and one of Northern New Mexico's largest selections of English and western saddles.",
    categorySlug: 'pet-supply', featured: false, tags: ['feed', 'independent', 'livestock'],
  },
  {
    name: '10,000 Wags Pet Resort',
    slug: '10000-wags-pet-resort-taos',
    city: 'Taos', citySlug: 'taos', state: 'NM',
    address: '24822 US-64, Taos, NM 87529',
    phone: '(575) 751-9247', website: 'https://10000wags.com',
    description: 'Taos-area pet resort providing safe overnight boarding for dogs and cats, daycare, grooming, and a retail boutique with a special small-dogs-only room.',
    categorySlug: 'boarding-daycare', featured: false, tags: ['boarding', 'grooming', 'boutique'],
  },
  {
    name: 'Hotel Willa',
    slug: 'hotel-willa-taos',
    city: 'Taos', citySlug: 'taos', state: 'NM',
    address: '233 Paseo Del Pueblo Sur, Taos, NM 87571',
    phone: '(575) 305-7711', website: 'https://www.hotelwilla.com',
    description: 'Boutique hotel in central Taos welcoming up to two dogs of any size at $100 each, with treats provided and pets allowed throughout the property on leash.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['boutique', 'dogs', 'luxury'],
  },
  {
    name: 'El Pueblo Lodge',
    slug: 'el-pueblo-lodge-taos',
    city: 'Taos', citySlug: 'taos', state: 'NM',
    address: '412 Paseo Del Pueblo Norte, Taos, NM 87571',
    phone: '(575) 758-8700', website: 'https://www.elpueblolodge.com',
    description: 'Casual Taos lodge welcoming both dogs and cats of any size in designated rooms for a modest pet fee, with pet-friendly outdoor spaces.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['dogs', 'cats', 'affordable'],
  },
  {
    name: 'Acacia Animal Hospital',
    slug: 'acacia-animal-hospital-tucson',
    city: 'Tucson', citySlug: 'tucson', state: 'AZ',
    address: '4205 N Campbell Ave, Tucson, AZ 85719',
    phone: '(520) 308-4225', website: 'https://acacia-vets.com',
    description: 'Independent veterinary hospital near River Road offering comprehensive wellness, urgent care, and emergency services for dogs and cats.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'emergency', 'dogs'],
  },
  {
    name: 'Catalina Pet Hospital',
    slug: 'catalina-pet-hospital-tucson',
    city: 'Tucson', citySlug: 'tucson', state: 'AZ',
    address: '3925 E Fort Lowell Rd Ste 107, Tucson, AZ 85712',
    phone: '(520) 795-4612', website: 'https://www.catalinapethospital.net',
    description: 'Well-established full-service small animal hospital providing comprehensive medical, surgical, and dental care to the Tucson area.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'surgery', 'dentistry'],
  },
  {
    name: 'Pantano Animal Clinic',
    slug: 'pantano-animal-clinic-tucson',
    city: 'Tucson', citySlug: 'tucson', state: 'AZ',
    address: '8333 E 22nd St, Tucson, AZ 85710',
    phone: '(520) 885-3594', website: 'https://pantanoac.com',
    description: 'Multi-doctor general practice veterinary hospital on Tucson\'s east side with advanced medical diagnostics and surgical capabilities.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'surgery', 'diagnostics'],
  },
  {
    name: 'OK Feed & Supply',
    slug: 'ok-feed-and-supply-tucson',
    city: 'Tucson', citySlug: 'tucson', state: 'AZ',
    address: '3701 E Fort Lowell Rd, Tucson, AZ 85716',
    phone: '(520) 325-0122', website: 'https://okfeedaz.com',
    description: 'Family-owned Tucson institution since 1936, carrying natural and holistic pet foods, alfalfa, straw, livestock supplies, and pet accessories.',
    categorySlug: 'pet-supply', featured: false, tags: ['independent', 'natural', 'feed'],
  },
  {
    name: 'Pawsitive Vibes',
    slug: 'pawsitive-vibes-tucson',
    city: 'Tucson', citySlug: 'tucson', state: 'AZ',
    address: '8591 N Silverbell Rd, Tucson, AZ 85743',
    phone: '(520) 344-9579', website: 'https://pawsitivevibestucson.com',
    description: 'Unique locally owned Tucson boutique offering quality dog and cat products, raw food, goat milk, and aquarium supplies unavailable at big-box retailers.',
    categorySlug: 'pet-supply', featured: false, tags: ['boutique', 'raw-food', 'independent'],
  },
  {
    name: 'Paw Commons Pet Resort Tucson',
    slug: 'paw-commons-pet-resort-tucson',
    city: 'Tucson', citySlug: 'tucson', state: 'AZ',
    address: '6211 E Speedway Blvd, Tucson, AZ 85712',
    phone: '(520) 477-4300', website: 'https://www.pawcommons.com/tucson-az',
    description: 'Premium east Tucson pet resort offering dog boarding, daycare, training, and full-service grooming in a professionally managed facility.',
    categorySlug: 'boarding-daycare', featured: false, tags: ['boarding', 'daycare', 'grooming'],
  },
  {
    name: 'Waggin Tail Inn',
    slug: 'waggin-tail-inn-tucson',
    city: 'Tucson', citySlug: 'tucson', state: 'AZ',
    address: '2535 N Rising Star Trail, Tucson, AZ 85745',
    phone: '(206) 498-8233', website: 'https://waggintailinn.com',
    description: "Family-run dog daycare and boarding facility on Tucson's west side, where dogs are treated as family in a home-like setting.",
    categorySlug: 'boarding-daycare', featured: false, tags: ['daycare', 'dogs', 'overnight'],
  },
  {
    name: 'Hotel McCoy',
    slug: 'hotel-mccoy-tucson',
    city: 'Tucson', citySlug: 'tucson', state: 'AZ',
    address: '720 W Silverlake Rd, Tucson, AZ 85713',
    phone: '(844) 782-9622', website: 'https://www.hotelmccoy.com',
    description: 'Locally celebrated art hotel with mid-century modern design and heated saltwater pool; allows two dogs of any size with a refundable deposit.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['boutique', 'dogs', 'art-hotel'],
  },
  {
    name: 'The Eddy Hotel Tucson',
    slug: 'the-eddy-hotel-tucson',
    city: 'Tucson', citySlug: 'tucson', state: 'AZ',
    address: '4626 N Campbell Ave, Tucson, AZ 85718',
    phone: '(520) 297-8624', website: 'https://www.theeddyhotel.com',
    description: 'Boutique Tapestry Collection hotel in central Tucson welcoming up to two dogs (combined 75 lbs) with a $75 pet fee per stay.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['boutique', 'dogs', 'full-service'],
  },
  {
    name: 'Animal Care Hospital of Phoenix',
    slug: 'animal-care-hospital-of-phoenix',
    city: 'Phoenix', citySlug: 'phoenix', state: 'AZ',
    address: '3131 E Thomas Rd, Phoenix, AZ 85016',
    phone: '(602) 955-5757', website: 'https://azvet.com',
    description: 'Long-established independent general practice veterinary hospital in Phoenix offering wellness exams, surgery, advanced diagnostics, and preventive care.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'surgery', 'diagnostics'],
  },
  {
    name: 'Village Animal Clinic Phoenix',
    slug: 'village-animal-clinic-phoenix',
    city: 'Phoenix', citySlug: 'phoenix', state: 'AZ',
    address: '3515 W Calavar Rd, Phoenix, AZ 85053',
    phone: '(602) 938-8500', website: 'https://www.villageanimalclinicphoenix.com',
    description: 'Neighborhood veterinary clinic in North Phoenix providing compassionate general practice care for dogs and cats.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'dogs', 'cats'],
  },
  {
    name: 'Pet Food Depot',
    slug: 'pet-food-depot-phoenix',
    city: 'Phoenix', citySlug: 'phoenix', state: 'AZ',
    address: '17645 N Cave Creek Rd, Phoenix, AZ 85032',
    phone: '(602) 493-7639', website: 'https://pfdepot.com',
    description: 'Family-owned and operated independent pet and feed store chain with multiple Phoenix-area locations carrying premium food, treats, and supplies.',
    categorySlug: 'pet-supply', featured: false, tags: ['natural', 'independent', 'feed'],
  },
  {
    name: 'Second Home Pet Resort Phoenix',
    slug: 'second-home-pet-resort-phoenix',
    city: 'Phoenix', citySlug: 'phoenix', state: 'AZ',
    address: '747 E Thunderbird Rd, Phoenix, AZ 85022',
    phone: '(602) 997-6600', website: 'https://www.secondhomepetresort.com',
    description: "Arizona's only all-suite mountainside pet resort offering individualized boarding, daycare, and grooming in a luxury setting.",
    categorySlug: 'boarding-daycare', featured: false, tags: ['luxury', 'boarding', 'suites'],
  },
  {
    name: 'Alta Vista Pet Boarding & Grooming',
    slug: 'alta-vista-pet-boarding-phoenix',
    city: 'Phoenix', citySlug: 'phoenix', state: 'AZ',
    address: '4730 N 7th Ave, Phoenix, AZ 85013',
    phone: '(602) 265-3198', website: 'https://www.altavistapetboarding.com',
    description: 'Centrally located Phoenix boarding and grooming facility offering personalized care for dogs in a safe, attentive environment.',
    categorySlug: 'boarding-daycare', featured: false, tags: ['boarding', 'grooming', 'dogs'],
  },
  {
    name: 'Kimpton Hotel Palomar Phoenix',
    slug: 'kimpton-hotel-palomar-phoenix',
    city: 'Phoenix', citySlug: 'phoenix', state: 'AZ',
    address: '2 E Jefferson St, Phoenix, AZ 85004',
    phone: '(602) 253-6633', website: 'https://www.hotelpalomar-phoenix.com',
    description: 'Downtown Phoenix boutique hotel with no pet size or weight restrictions, providing dog beds, water bowls, and a pet-friendly concierge list at no extra pet fee.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['boutique', 'dogs', 'no-fee'],
  },
  {
    name: 'The Clarendon Hotel and Spa',
    slug: 'the-clarendon-hotel-phoenix',
    city: 'Phoenix', citySlug: 'phoenix', state: 'AZ',
    address: '401 W Clarendon Ave, Phoenix, AZ 85013',
    phone: '(602) 252-7363', website: 'https://www.goclarendon.com',
    description: 'Urban Phoenix boutique hotel with rooftop pool and outdoor spa welcoming up to two pets at $25 per night each.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['boutique', 'dogs', 'rooftop-pool'],
  },
  {
    name: 'Flagstaff Veterinary Clinic',
    slug: 'flagstaff-veterinary-clinic',
    city: 'Flagstaff', citySlug: 'flagstaff', state: 'AZ',
    address: '963 W Route 66, Flagstaff, AZ 86001',
    phone: '(928) 361-0963', website: 'https://www.flagvet.com',
    description: 'Family-owned Flagstaff clinic offering same-day urgent care, wellness exams, surgery, and emergency services for dogs and cats.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'urgent-care', 'independent'],
  },
  {
    name: 'Canyon Pet Hospital',
    slug: 'canyon-pet-hospital-flagstaff',
    city: 'Flagstaff', citySlug: 'flagstaff', state: 'AZ',
    address: '1054 E Old Canyon Ct, Flagstaff, AZ 86001',
    phone: '(928) 774-5197', website: 'https://canyonpet.com',
    description: 'Premier Northern Arizona veterinary hospital open seven days a week with 24-hour emergency on-call service, providing quality contemporary medicine.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['emergency', 'wellness', 'surgery'],
  },
  {
    name: 'Midtown Animal Clinic Flagstaff',
    slug: 'midtown-animal-clinic-flagstaff',
    city: 'Flagstaff', citySlug: 'flagstaff', state: 'AZ',
    address: '1359 E Butler Ave, Flagstaff, AZ 86001',
    phone: '(928) 440-4020', website: 'https://www.midtown.vet',
    description: 'Voted Best of Flag, this fiercely independent single-owner practice manages nearly everything in-house and provides personalized veterinary care for dogs and cats.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'independent', 'dogs'],
  },
  {
    name: "Olsen's Grain Flagstaff",
    slug: 'olsens-grain-flagstaff',
    city: 'Flagstaff', citySlug: 'flagstaff', state: 'AZ',
    address: '2250 N Steves Blvd, Flagstaff, AZ 86004',
    phone: '(928) 522-0568', website: 'https://olsensgrain.com',
    description: "Northern Arizona's destination for healthy, holistic pet food and treats, plus livestock and specialty pet supplies, with expert staff guidance.",
    categorySlug: 'pet-supply', featured: false, tags: ['natural', 'holistic', 'independent'],
  },
  {
    name: 'Cinder Hills Kennels',
    slug: 'cinder-hills-kennels-flagstaff',
    city: 'Flagstaff', citySlug: 'flagstaff', state: 'AZ',
    address: '11110 Townsend Winona Rd, Flagstaff, AZ 86004',
    phone: '(928) 526-3812', website: 'https://www.cinderhillskennels.com',
    description: "Flagstaff's premier pet boarding facility offering dog and cat boarding and doggie daycare in a safe, well-staffed environment.",
    categorySlug: 'boarding-daycare', featured: false, tags: ['boarding', 'daycare', 'cats'],
  },
  {
    name: 'Aspen Veterinary Clinic Flagstaff',
    slug: 'aspen-veterinary-clinic-flagstaff',
    city: 'Flagstaff', citySlug: 'flagstaff', state: 'AZ',
    address: '7861 N Hwy 89, Flagstaff, AZ 86004',
    phone: '(928) 526-2423', website: 'https://www.aspenvetflagstaff.com',
    description: 'Family-run Flagstaff clinic serving the community for over 50 years, offering small and large animal general practice plus equine wellness and emergency care.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'large-animals', 'equine'],
  },
  {
    name: 'Arizona Mountain Inn & Cabins',
    slug: 'arizona-mountain-inn-flagstaff',
    city: 'Flagstaff', citySlug: 'flagstaff', state: 'AZ',
    address: '4200 Lake Mary Rd, Flagstaff, AZ 86005',
    phone: '(928) 774-8959', website: 'https://arizonamountaininn.com',
    description: 'Forested B&B and cabin retreat near Flagstaff allowing two pets of any size in designated accommodations for $20 per pet per night.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['cabins', 'dogs', 'cats'],
  },
  {
    name: 'SpringHill Suites Flagstaff',
    slug: 'springhill-suites-flagstaff',
    city: 'Flagstaff', citySlug: 'flagstaff', state: 'AZ',
    address: '1000 W Route 66, Flagstaff, AZ 86001',
    phone: '(928) 774-8042', website: 'https://www.marriott.com/en-us/hotels/flgsh-springhill-suites-flagstaff',
    description: 'All-suite Marriott property in downtown Flagstaff welcoming up to two pets up to 100 lbs each for a flat $75 pet stay fee.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['dogs', 'cats', 'suites'],
  },
  {
    name: 'Urban Vet Care',
    slug: 'urban-vet-care-denver',
    city: 'Denver', citySlug: 'denver', state: 'CO',
    address: '2815 Clay St, Denver, CO 80211',
    phone: '(303) 477-1984', website: 'https://urbanvetcare.com',
    description: 'Independent, woman-owned AAHA-accredited clinic in LoHi/Highlands with comprehensive full-service care for dogs and cats.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'aaha-accredited', 'independent'],
  },
  {
    name: 'Highlands Animal Clinic',
    slug: 'highlands-animal-clinic-denver',
    city: 'Denver', citySlug: 'denver', state: 'CO',
    address: '3727 W 32nd Ave, Denver, CO 80211',
    phone: '(303) 455-7387', website: 'https://highlandsanimalclinic.com',
    description: "Boutique veterinary practice in a restored 1890s Victorian in Denver's Highlands Square, offering comprehensive wellness and medical care.",
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'independent', 'boutique'],
  },
  {
    name: 'Simpawtico',
    slug: 'simpawtico-denver',
    city: 'Denver', citySlug: 'denver', state: 'CO',
    address: '4500 W 38th Ave Suite 110, Denver, CO 80212',
    phone: '(720) 381-6819', website: 'https://www.simpawtico.com',
    description: "Locally owned independent pet store in Denver's Highlands neighborhood carrying healthy foods, treats, toys, supplements, and beds for dogs and cats.",
    categorySlug: 'pet-supply', featured: false, tags: ['natural', 'independent', 'boutique'],
  },
  {
    name: 'Mouthfuls Pet Supply',
    slug: 'mouthfuls-pet-supply-denver',
    city: 'Denver', citySlug: 'denver', state: 'CO',
    address: '4224 Tennyson St, Denver, CO 80212',
    phone: '(720) 855-7505', website: 'https://mouthfuls.net',
    description: "Berkeley neighborhood's award-winning pet boutique with a bakery case, bone-shaped treat tasting bar, and a wall of unique toys for dogs and cats.",
    categorySlug: 'pet-supply', featured: false, tags: ['boutique', 'treats', 'independent'],
  },
  {
    name: 'Happy Dog Daycare Denver',
    slug: 'happy-dog-daycare-denver',
    city: 'Denver', citySlug: 'denver', state: 'CO',
    address: '3939 Newport St, Denver, CO 80207',
    phone: '(303) 331-1364', website: 'https://happydogdenver.com',
    description: "Denver's beloved neighborhood dog daycare offering safe, enriching socialization and care in a friendly, home-like atmosphere.",
    categorySlug: 'boarding-daycare', featured: false, tags: ['daycare', 'dogs', 'socialization'],
  },
  {
    name: 'Hounds Town Denver-Baker',
    slug: 'hounds-town-denver-baker',
    city: 'Denver', citySlug: 'denver', state: 'CO',
    address: '52 W Iowa Ave, Denver, CO 80223',
    phone: '(303) 862-8202', website: 'https://houndstownusa.com/locations/denver-baker',
    description: "Interactive cage-free dog boarding and daycare in Denver's Baker neighborhood, with enrichment activities and socialization throughout the day.",
    categorySlug: 'boarding-daycare', featured: false, tags: ['boarding', 'cage-free', 'dogs'],
  },
  {
    name: 'Kimpton Hotel Monaco Denver',
    slug: 'kimpton-hotel-monaco-denver',
    city: 'Denver', citySlug: 'denver', state: 'CO',
    address: '1717 Champa St, Denver, CO 80202',
    phone: '(303) 296-1717', website: 'https://www.monaco-denver.com',
    description: 'Iconic boutique downtown Denver hotel with no pet fees, size, or breed restrictions, offering pet beds, water bowls, and a pet-friendly concierge list.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['boutique', 'no-fee', 'dogs'],
  },
  {
    name: 'Hotel Teatro Denver',
    slug: 'hotel-teatro-denver',
    city: 'Denver', citySlug: 'denver', state: 'CO',
    address: '1100 14th St, Denver, CO 80202',
    phone: '(303) 228-1100', website: 'https://hotelteatro.com',
    description: "Denver's most dog-friendly boutique hotel welcoming two dogs of any size for free, with pet goodie bags, beds, and bowls available on request.",
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['boutique', 'dogs', 'no-fee'],
  },
  {
    name: 'Durango Animal Hospital',
    slug: 'durango-animal-hospital',
    city: 'Durango', citySlug: 'durango', state: 'CO',
    address: '140 Rock Point Dr, Durango, CO 81301',
    phone: '(970) 247-3174', website: 'https://durangovet.com',
    description: 'Full-service small animal and exotic pet general practice in Durango offering medicine, surgery, and wellness care for dogs, cats, and exotics.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'exotics', 'surgery'],
  },
  {
    name: 'Kindness Animal Hospital',
    slug: 'kindness-animal-hospital-durango',
    city: 'Durango', citySlug: 'durango', state: 'CO',
    address: '2518 Hwy 172, Durango, CO 81303',
    phone: '(970) 259-3788', website: 'https://kindnessanimal.com',
    description: 'Dedicated small animal practice in Durango open since 2007, providing caring veterinary services exclusively for dogs and cats.',
    categorySlug: 'veterinary-clinics', featured: false, tags: ['wellness', 'dogs', 'cats'],
  },
  {
    name: 'Creature Comforts Durango',
    slug: 'creature-comforts-durango',
    city: 'Durango', citySlug: 'durango', state: 'CO',
    address: '305 S Camino Del Rio, Durango, CO 81303',
    phone: '(970) 247-2748', website: 'https://creaturecomfortsdurango.com',
    description: "Durango's biggest and best pet supply retailer for over 34 years, offering expert dog trainers, premium food, and the area's most comprehensive pet supply selection.",
    categorySlug: 'pet-supply', featured: false, tags: ['independent', 'training', 'full-service'],
  },
  {
    name: 'Healthy Hounds & Fat Cats',
    slug: 'healthy-hounds-and-fat-cats-durango',
    city: 'Durango', citySlug: 'durango', state: 'CO',
    address: '571 Turner Dr, Durango, CO 81303',
    phone: '(970) 375-9700', website: 'https://www.healthyhoundsandfatcats.com',
    description: "Durango's go-to doggie daycare and boarding facility with roomy kennels, indoor and outdoor play space, grooming, and a self-service dog wash.",
    categorySlug: 'boarding-daycare', featured: false, tags: ['daycare', 'boarding', 'grooming'],
  },
  {
    name: 'Rochester Hotel',
    slug: 'rochester-hotel-durango',
    city: 'Durango', citySlug: 'durango', state: 'CO',
    address: '726 E 2nd Ave, Durango, CO 81301',
    phone: '(970) 764-0035', website: 'https://rochesterhotel.com',
    description: 'Historic downtown Durango boutique hotel welcoming dogs in designated pet-friendly rooms for a $20 per-pet-per-night fee.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['boutique', 'dogs', 'historic'],
  },
  {
    name: 'DoubleTree by Hilton Durango',
    slug: 'doubletree-durango',
    city: 'Durango', citySlug: 'durango', state: 'CO',
    address: '501 Camino Del Rio, Durango, CO 81301',
    phone: '(970) 259-6580', website: 'https://www.hilton.com/en/hotels/durcodt-doubletree-durango',
    description: 'Full-service hotel along the Animas River welcoming two pets of any size for $40 per night, with bowls and treats at the front desk.',
    categorySlug: 'pet-friendly-lodging', featured: false, tags: ['dogs', 'cats', 'full-service'],
  },
];

const client = new Client(process.env.DB_URL);
await client.connect();

// Load region and category lookup tables
const { rows: regionRows } = await client.query('SELECT id, slug FROM regions');
const { rows: categoryRows } = await client.query('SELECT id, slug FROM categories');
const regionMap = Object.fromEntries(regionRows.map(r => [r.slug, r.id]));
const categoryMap = Object.fromEntries(categoryRows.map(r => [r.slug, r.id]));

// Collect all unique tag slugs
const allTagSlugs = [...new Set(listings.flatMap(l => l.tags))];
for (const tagSlug of allTagSlugs) {
  await client.query(
    'INSERT INTO tags (name, slug) VALUES ($1, $2) ON CONFLICT (slug) DO NOTHING',
    [tagSlug.replace(/-/g, ' '), tagSlug]
  );
}
const { rows: tagRows } = await client.query('SELECT id, slug FROM tags');
const tagMap = Object.fromEntries(tagRows.map(r => [r.slug, r.id]));

let inserted = 0;
let skipped = 0;

for (const listing of listings) {
  const regionId = regionMap[listing.citySlug];
  const categoryId = categoryMap[listing.categorySlug];

  if (!regionId) { console.error(`No region for citySlug: ${listing.citySlug}`); skipped++; continue; }
  if (!categoryId) { console.error(`No category for slug: ${listing.categorySlug}`); skipped++; continue; }

  const { rows } = await client.query(
    `INSERT INTO listings (name, slug, region_id, city, state, address, phone, website, description, featured, verified)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
     ON CONFLICT (slug) DO NOTHING
     RETURNING id`,
    [listing.name, listing.slug, regionId, listing.city, listing.state,
     listing.address, listing.phone, listing.website, listing.description,
     listing.featured, true]
  );

  if (rows.length === 0) { skipped++; continue; }
  const listingId = rows[0].id;

  await client.query(
    'INSERT INTO listing_categories (listing_id, category_id) VALUES ($1,$2) ON CONFLICT DO NOTHING',
    [listingId, categoryId]
  );

  for (const tagSlug of listing.tags) {
    const tagId = tagMap[tagSlug];
    if (tagId) {
      await client.query(
        'INSERT INTO listing_tags (listing_id, tag_id) VALUES ($1,$2) ON CONFLICT DO NOTHING',
        [listingId, tagId]
      );
    }
  }

  inserted++;
}

await client.end();
console.log(`Done — ${inserted} inserted, ${skipped} skipped`);
